version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Tuesdays
      day: "tuesday"
    open-pull-requests-limit: 40
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "nanoid"
        # nanoid v4 drops support for commonJs and I had real difficulty getting it to work with Jest. Clip at v3 for now and re-evaluate for v6
        versions: ["4.x", "5.x"]
      - dependency-name: "query-string"
        # query-string v8 drops support for commonJs and I had real difficulty getting it to work with Jest. Clip at v7 for now and re-evaluate for v9
        versions: ["8.x"]
      - dependency-name: "date-fns"
        # neither date-fns v2, nor date-fns-tz `format` function seem to be able to emulate the same behaviour as date-fns v1 `format`.
        versions: ["2.x"]
      # These all need updating but have known breaking changes and are being ignored to avoid noise and $$ in CI 
      - dependency-name: "change-case"
        versions: ["5.x"]
