defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:20

version: 2.1
orbs:
  untracked_changes: niteo/check-untracked-changes@1.0.0
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"
  install:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Npm install"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Build app"
          command: npm run build
      - run:
          name: "Build docs"
          command: npm run doc
      - run:
          name: "Reset search.js caused by gzip non-determinism"
          command: git checkout -- docs/assets/search.js
      - run:
          name: "Reset navigation.js caused by gzip non-determinism"
          command: git checkout -- docs/assets/navigation.js
      - untracked_changes/check
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - package.json
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Setup fake env vars for testing."
          command: cp .env-template .env
      - run:
          name: "Running eslint validation."
          command: npm run lint
      - run:
          name: "Running jest test suite."
          command: npm run test
workflows:
  build_and_deploy:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - build:
          requires:
            - install
      - test:
          requires:
            - build
